/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Sandro
 */
public class TitanPlyer extends javax.swing.JFrame {

    /**
     * Creates new form TitanPlyer
     */
    public TitanPlyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFrame();
        loadFileChooser = new javax.swing.JFileChooser();
        Background = new javax.swing.JPanel();
        AddSongButton = new javax.swing.JButton();
        RemoveSongButton = new javax.swing.JButton();
        SongInformationBox = new javax.swing.JTextField();
        CreatePlayListButton = new javax.swing.JButton();
        DeletePlayListButton = new javax.swing.JButton();
        SelectPlayListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlayListInformationBox = new javax.swing.JTextArea();
        PausedButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        GoNextButton = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        openPlayListOption = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        addSongOption = new javax.swing.JMenuItem();
        removeSongOption = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        createPlayListOption = new javax.swing.JMenuItem();
        deletePlayListOption = new javax.swing.JMenuItem();

        loadFileChooser.setFileFilter(new MyCustomFilter());
        loadFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FileChooserLayout = new javax.swing.GroupLayout(FileChooser.getContentPane());
        FileChooser.getContentPane().setLayout(FileChooserLayout);
        FileChooserLayout.setHorizontalGroup(
            FileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        FileChooserLayout.setVerticalGroup(
            FileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setForeground(new java.awt.Color(255, 255, 255));

        AddSongButton.setText("Add a Song");

        RemoveSongButton.setText("Remove a Song");

        SongInformationBox.setText("MP3 File's Information");

        CreatePlayListButton.setText("Create a Play List");

        DeletePlayListButton.setText("Delete a Play List");

        SelectPlayListButton.setText("Select a Play List");

        PlayListInformationBox.setColumns(20);
        PlayListInformationBox.setRows(5);
        jScrollPane1.setViewportView(PlayListInformationBox);

        PausedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/paused.jpg"))); // NOI18N
        PausedButton.setText("jButton2");

        PlayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/play.jpg"))); // NOI18N
        PlayButton.setText("jButton3");

        StopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/stop.jpg"))); // NOI18N
        StopButton.setText("jButton4");

        GoBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/goback.jpg"))); // NOI18N
        GoBackButton.setText("jButton1");

        GoNextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/gonext.jpg"))); // NOI18N
        GoNextButton.setText("jButton1");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(AddSongButton)
                        .addGap(28, 28, 28)
                        .addComponent(RemoveSongButton)
                        .addContainerGap())
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(CreatePlayListButton)
                                    .addComponent(SelectPlayListButton)
                                    .addComponent(DeletePlayListButton)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(PausedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(GoNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SongInformationBox, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(CreatePlayListButton)
                        .addGap(41, 41, 41)
                        .addComponent(SelectPlayListButton)
                        .addGap(36, 36, 36)
                        .addComponent(DeletePlayListButton)
                        .addGap(207, 207, 207))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSongButton)
                    .addComponent(RemoveSongButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(SongInformationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GoNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PausedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        jMenu1.setText("File");

        exitOption.setText("Exit");
        exitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionActionPerformed(evt);
            }
        });
        jMenu1.add(exitOption);

        Menu.add(jMenu1);

        jMenu2.setText("Play-List");

        openPlayListOption.setText("Open Play-List");
        jMenu2.add(openPlayListOption);
        jMenu2.add(jSeparator2);

        addSongOption.setText("Add a Song");
        addSongOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongOptionActionPerformed(evt);
            }
        });
        jMenu2.add(addSongOption);

        removeSongOption.setText("Remove a Song");
        jMenu2.add(removeSongOption);
        jMenu2.add(jSeparator1);

        createPlayListOption.setText("Create Play-List");
        jMenu2.add(createPlayListOption);

        deletePlayListOption.setText("Delete Play-List");
        jMenu2.add(deletePlayListOption);

        Menu.add(jMenu2);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitOptionActionPerformed

    private void loadFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileChooserActionPerformed
        
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loadFileChooserActionPerformed

    private void addSongOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongOptionActionPerformed
 
        loadFileChooser.setCurrentDirectory(new File("."));
        loadFileChooser.showOpenDialog(Background);
        
    }//GEN-LAST:event_addSongOptionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitanPlyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitanPlyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitanPlyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitanPlyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TitanPlyer().setVisible(true);
            }
        });
    }
    
    class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".mp3");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "MP3 Files (*.mp3)";
        }
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSongButton;
    private javax.swing.JPanel Background;
    private javax.swing.JButton CreatePlayListButton;
    private javax.swing.JButton DeletePlayListButton;
    private javax.swing.JFrame FileChooser;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JButton GoNextButton;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton PausedButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JTextArea PlayListInformationBox;
    private javax.swing.JButton RemoveSongButton;
    private javax.swing.JButton SelectPlayListButton;
    private javax.swing.JTextField SongInformationBox;
    private javax.swing.JButton StopButton;
    private javax.swing.JMenuItem addSongOption;
    private javax.swing.JMenuItem createPlayListOption;
    private javax.swing.JMenuItem deletePlayListOption;
    private javax.swing.JMenuItem exitOption;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JFileChooser loadFileChooser;
    private javax.swing.JMenuItem openPlayListOption;
    private javax.swing.JMenuItem removeSongOption;
    // End of variables declaration//GEN-END:variables
}
